class NotFound(Exception):
    pass

class LoginError(Exception):
    pass